### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by ChuanQin** [THUYimingLi/Untargeted_Backdoor_Watermark#2]
Hi~I'm running train_UBW_P.py with torch 1.13.1+cu117 and python 3.7
receive such error when calling "./UBW-P/core/attacks/base.py", line 196, in train: loss.backward()

would u mind providing the python, torch and cuda version u r using?

**Comment by ChuanQin** [comment]
I've solved this problem, torch 1.12.1, torchvision 0.13.1 and python 3.7. i'm not quite sure the version of my cudatoolkit, but with "nvidia-smi" command the cuda version reads 11.4
